[package]
name = "soundcloud-fs"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
clap = "2.32.0"
env_logger = "*"
failure = "*"
failure_derive = "*"
fuse = "0.3.1"
libc = "*"
log = "*"
reqwest = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "*"
