[package]
name = "soundcloud-fs"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
env_logger = "*"
failure = "*"
failure_derive = "*"
fuse = "0.3.1"
libc = "*"
log = "*"
soundcloud = { path = "./soundcloud" }
time = "*"

[workspace]
members = [
	"soundcloud"
]
