[package]
name = "soundcloud-fs"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"
chrono = "0.4.6"
clap = "2.32.0"
env_logger = "*"
failure = "0.1.3"
failure_derive = "0.1.3"
fuse = "0.3.1"
id3 = "0.2.5"
lazy_static = "1.2.0"
libc = "0.2.44"
log = "0.4.6"
nix = "0.12.0"
soundcloud = { path = "./soundcloud" }
time = "0.1.40"

[workspace]
members = [
	"soundcloud"
]
