[package]
name = "soundcloud"
version = "0.1.0"
authors = ["polyfloyd <floyd@polyfloyd.net>"]

[dependencies]
chrono = "*"
failure = "*"
failure_derive = "*"
id3 = "0.2.5"
lazy_static = "1.2.0"
log = "*"
reqwest = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
